# With GitHub Pages Gem
remote_theme: chrisrhymes/bulma-clean-theme

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      fixed_navbar: top
      menubar_toc: true
      # layout: "default"
