[package]
name = "https-server"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = { version = "4", features = ["openssl"]   } # Use actix-web to implement a backend server
env_logger = "0.9" # for logging
openssl = "0.10" # for TLS

actix-files = "0.6.0" # For file serving
